name: Release CheapDesign

on:
  push:
    branches: [ "main" ]
    paths:
      - "version.txt"
      - "pack/**"

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          VERSION=$(cat version.txt | tr -d '\n')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # -------- ZIP BUILD --------
      - name: Build Java texture packs
        run: |
          cd pack
          zip -r ../CheapDesign-${{ steps.version.outputs.version }}.zip .
          cd ..
          cp CheapDesign-${{ steps.version.outputs.version }}.zip CheapMC-${{ steps.version.outputs.version }}.zip

      # -------- GITHUB RELEASE --------
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: CheapDesign ${{ steps.version.outputs.version }}
          files: |
            CheapDesign-${{ steps.version.outputs.version }}.zip
            CheapMC-${{ steps.version.outputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
